Repository AY2425S2-CS2103T-T12-4/tp, pull requests merged in 2025-04, with the labels that each got.

#181 Branch nothing to clear
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/ConfirmCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
Labels: severity.High

#194 Update initialisation to use valid address book
  src/main/java/seedu/address/MainApp.java
Labels: type.Bug, severity.High

#185 Fix invalid input for appointment date in find command
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
Labels: priority.Medium

#173 DG implementation update
  docs/DeveloperGuide.md
  docs/diagrams/UpcomingAppointmentClassDiagram.puml
  docs/images/UpcomingAppointmentClassDiagram.png
Labels: type.Task

#197 Fix bug
  src/main/java/seedu/address/logic/commands/AbortCommand.java
Labels: severity.High

#206 Edit command bug
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: priority.High, type.Bug, severity.High

#211 Release fix
  build.gradle
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/AppointmentDateContainsKeywordsPredicate.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/LightTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: priority.High

#220 Fix some part of UML diagram
  docs/diagrams/BetterModelClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
Labels: priority.Medium

#219 Fix find command errors
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: alpha-bug

#222 Edit DG
  docs/DeveloperGuide.md
  docs/diagrams/UndoRedoState2.puml
  docs/images/UndoRedoState2.png
Labels: priority.Medium

#236 Developer guide and user guide update
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.High

#246 Edit delete portion of UG
  docs/UserGuide.md
Labels: priority.Medium

#243 Update UG to add a glossary
  docs/UserGuide.md
Labels: priority.Low

#244 Update developer guide
  docs/DeveloperGuide.md
Labels: priority.High

#248 Update known issues in UG
  docs/UserGuide.md
Labels: priority.High

#255 Update UG style
  docs/UserGuide.md
  docs/images/lightThemeExample.png
Labels: priority.Medium

#323 Fix appointment date
  src/main/java/seedu/address/model/person/AppointmentDate.java
Labels: priority.High
